---
language: python
python:
- '3.6'
- '3.7'
- '3.8'
env:
# Each version of NetBox listed here uses configuration stored in development/configuration.py
  matrix:
  - NETBOX_VER=v2.8.9
  - NETBOX_VER=v2.9.11
  - NETBOX_VER=v2.10.10
  - NETBOX_VER=v2.11.10

services:
- docker
# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_script:
- pip install invoke docker-compose
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry.py
- python /tmp/get-poetry.py -y --version 1.0.2
- source $HOME/.poetry/env

script:
- invoke build --python-ver $TRAVIS_PYTHON_VERSION
- invoke tests --python-ver $TRAVIS_PYTHON_VERSION
# --------------------------------------------------------------------------
# Deploy
# --------------------------------------------------------------------------
deploy:
  provider: script
  script: poetry config pypi-token.pypi $PYPI_TOKEN && poetry publish --build
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: $NETBOX_VER = v2.9.11
    python: 3.7
